### ISSUE TITLE
'npm start' failed

### ISSUE THREAD

**Issue by sajidali** [djdjalas/EcmaScript2015Explained#1]
Tried to follow the instructions, but it failed at `npm start`

Error shown as result of `npm start` command:
```
npm start

> es6-new-features@1.0.0 start /var/www/html/EcmaScript2015Explained
> webpack-dev-server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

following is the contents of npm-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle es6-new-features@1.0.0~prestart: es6-new-features@1.0.0
6 silly lifecycle es6-new-features@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle es6-new-features@1.0.0~start: es6-new-features@1.0.0
8 verbose lifecycle es6-new-features@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle es6-new-features@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/EcmaScript2015Explained/node_modules/.bin:/usr/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/bin
10 verbose lifecycle es6-new-features@1.0.0~start: CWD: /var/www/html/EcmaScript2015Explained
11 silly lifecycle es6-new-features@1.0.0~start: Args: [ '-c', 'webpack-dev-server' ]
12 silly lifecycle es6-new-features@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle es6-new-features@1.0.0~start: Failed to exec start script
14 verbose stack Error: es6-new-features@1.0.0 start: `webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid es6-new-features@1.0.0
16 verbose cwd /var/www/html/EcmaScript2015Explained
17 error Linux 4.4.0-57-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.9.4
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error es6-new-features@1.0.0 start: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the es6-new-features@1.0.0 start script 'webpack-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the es6-new-features package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs es6-new-features
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls es6-new-features
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sajidali** [comment]
Error: listen EADDRINUSE 127.0.0.1:3000

port was already in use.
